//! World definitions loaded from one source document.

use serde::{Deserialize, Serialize};

use super::{
    animal_health::{
        DiseaseDefinition, RampageRule, TranquilizerDefinition, TranquilizerModePolicy,
        TreatmentDefinition,
    },
    animal_shows_and_training::{
        ShowAudioCue, ShowEditorPresentationPolicy, ShowPlatformUpgradePolicy,
        ShowPresentationIcon, ShowPresentationPolicy, ShowRuleDefinition, ShowSchedulingPolicy,
        ShowScoringPolicy, ShowStageDefinition, TrickDefinition, TrickOutcomeTokens,
    },
    aquatic_habitats::{
        AquaticRequirement, TankDefinition, TankDepthPolicy, TankEditPolicy, TankSurfacePolicy,
    },
    biomes_locations_and_details::{
        BiomeDefinition, BiomeDetailPlacementPolicy, WorldLocationDefinition,
    },
    camera_definitions::CameraTuningDefinition,
    catalogue_and_progression::{
        animal_adoption_offer_definition_types::AnimalAdoptionOfferConfiguration,
        catalogue_definition_types::CatalogueEntry,
        research_and_unlock_definition_types::{ResearchDefinition, UnlockDefinition},
        zoo_rating_fame_and_award_definition_types::{
            AwardDefinition, FameThreshold, RatingDefinition,
        },
        zoopedia_entry_types::ZoopediaEntry,
    },
    environment::{AmbientSpawnDefinition, EnvironmentDefinition, WeatherDefinition},
    extinct_animal_recovery::{
        CloningCenterDefinition, FossilPieceDefinition, FossilPlacementPolicy, FossilSetDefinition,
        FossilSlotDefinition,
    },
    facilities_and_maintenance::{CleanlinessPolicy, FacilityDefinition, MaintenanceDefinition},
    fences_and_gates::FenceDefinition,
    guest_simulation_definitions::{
        GuestDefinition, GuestGenerationPolicy, GuestViewingPolicy, PersonNamePool,
        ViewingOpportunityDefinition,
    },
    immersive_mode_policy::ImmersiveModePolicy,
    object_placement::PlaceableDefinition,
    paths_and_tile_surfaces::GuestPathDefinition,
    simulation_time::SimulationTimingDefinition,
    staff_management::{
        StaffAquaticTankWaterCleaningPolicy, StaffJobDefinition, StaffManagerPolicy,
        StaffRequestControllerDefinition, StaffRoleDefinition,
    },
    terrain_editing_brushes::TerrainEditingBrushDefinition,
    transportation_and_tours::{
        TourScoringPolicy, TourViewDefinition, TransportationStationDefinition,
        TransportationTrackDefinition, TransportationVehicleDefinition,
        TransportationVehicleSeatDefinition,
    },
    world_objects::WorldObjectDefinition,
};

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct WorldDefinitionDocument {
    pub objects: Vec<WorldObjectDefinition>,
    pub placeables: Vec<PlaceableDefinition>,
    pub facilities: Vec<FacilityDefinition>,
    pub maintenance_definitions: Vec<MaintenanceDefinition>,
    pub cleanliness_policy: Option<CleanlinessPolicy>,
    pub staff: Vec<StaffRoleDefinition>,
    pub staff_jobs: Vec<StaffJobDefinition>,
    pub staff_requests: Vec<StaffRequestControllerDefinition>,
    pub staff_manager: Option<StaffManagerPolicy>,
    pub guests: Vec<GuestDefinition>,
    pub guest_viewing: Option<GuestViewingPolicy>,
    pub viewing_opportunities: Vec<ViewingOpportunityDefinition>,
    pub fences: Vec<FenceDefinition>,
    pub paths: Vec<GuestPathDefinition>,
    pub biomes: Vec<BiomeDefinition>,
    pub locations: Vec<WorldLocationDefinition>,
    pub biome_detail_placement: Option<BiomeDetailPlacementPolicy>,
    pub brushes: Vec<TerrainEditingBrushDefinition>,
    pub diseases: Vec<DiseaseDefinition>,
    pub treatments: Vec<TreatmentDefinition>,
    pub tranquilizers: Vec<TranquilizerDefinition>,
    pub tranquilizer_mode: Option<TranquilizerModePolicy>,
    pub rampage_rules: Vec<RampageRule>,
    pub catalogue: Vec<CatalogueEntry>,
    pub animal_adoption_offer_configuration: Option<AnimalAdoptionOfferConfiguration>,
    pub zoopedia: Vec<ZoopediaEntry>,
    pub research: Vec<ResearchDefinition>,
    pub unlocks: Vec<UnlockDefinition>,
    pub rating_definitions: Vec<RatingDefinition>,
    pub fame_thresholds: Vec<FameThreshold>,
    pub awards: Vec<AwardDefinition>,
    pub tanks: Vec<TankDefinition>,
    pub aquatic_requirements: Vec<AquaticRequirement>,
    pub show_stages: Vec<ShowStageDefinition>,
    pub show_platform_upgrades: Option<ShowPlatformUpgradePolicy>,
    pub tricks: Vec<TrickDefinition>,
    pub trick_outcome_tokens: Vec<TrickOutcomeTokens>,
    pub show_rules: Vec<ShowRuleDefinition>,
    pub stations: Vec<TransportationStationDefinition>,
    pub tracks: Vec<TransportationTrackDefinition>,
    pub vehicles: Vec<TransportationVehicleDefinition>,
    pub vehicle_seats: Vec<TransportationVehicleSeatDefinition>,
    pub tour_views: Vec<TourViewDefinition>,
    pub fossil_sets: Vec<FossilSetDefinition>,
    pub fossil_pieces: Vec<FossilPieceDefinition>,
    pub fossil_slots: Vec<FossilSlotDefinition>,
    pub fossil_placement: Option<FossilPlacementPolicy>,
    pub cloning_centers: Vec<CloningCenterDefinition>,
    pub immersive_mode_policies: Vec<ImmersiveModePolicy>,
    pub cameras: Vec<CameraTuningDefinition>,
    pub simulation_timing: Option<SimulationTimingDefinition>,
    pub guest_generation: Option<GuestGenerationPolicy>,
    #[serde(default)]
    pub behavior_selection_policy:
        Option<super::behavior_selection_policy::BehaviorSelectionPolicy>,
    pub admission_price_bands_cents: Option<[i32; 4]>,
    pub tank_surface_policy: Option<TankSurfacePolicy>,
    pub tank_depth_policy: Option<TankDepthPolicy>,
    pub tank_edit_policy: Option<TankEditPolicy>,
    pub show_presentation: Option<ShowPresentationPolicy>,
    pub show_scheduling: Option<ShowSchedulingPolicy>,
    pub show_scoring: Option<ShowScoringPolicy>,
    pub show_audio_cues: Vec<ShowAudioCue>,
    pub show_editor_presentation: Option<ShowEditorPresentationPolicy>,
    pub show_presentation_icons: Vec<ShowPresentationIcon>,
    pub tour_scoring: Option<TourScoringPolicy>,
    pub staff_water_cleaning: Option<StaffAquaticTankWaterCleaningPolicy>,
    pub person_name_pools: Vec<PersonNamePool>,
    pub weather: Vec<WeatherDefinition>,
    pub ambient_spawns: Vec<AmbientSpawnDefinition>,
    pub environments: Vec<EnvironmentDefinition>,
}
